import { createContext, useContext, useEffect, useState } from "react";
export const languages = [
  { code:"en", name:"English", native:"English", flag:"" },
  { code:"hi", name:"Hindi", native:"हिन्दी", flag:"" },
  { code:"bn", name:"Bengali", native:"বাংলা", flag:"" },
  { code:"te", name:"Telugu", native:"తెలుగు", flag:"" },
  { code:"mr", name:"Marathi", native:"मराठी", flag:"" },
  { code:"ta", name:"Tamil", native:"தமிழ்", flag:"" },
  { code:"gu", name:"Gujarati", native:"ગુજરાતી", flag:"" },
  { code:"ur", name:"Urdu", native:"اردو", flag:"" },
  { code:"kn", name:"Kannada", native:"ಕನ್ನಡ", flag:"" },
  { code:"ml", name:"Malayalam", native:"മലയാളം", flag:"" },
  { code:"or", name:"Odia", native:"ଓଡ଼ିଆ", flag:"" },
  { code:"pa", name:"Punjabi", native:"ਪੰਜਾਬੀ", flag:"" },
  { code:"as", name:"Assamese", native:"অসমীয়া", flag:"" },
  { code:"mai", name:"Maithili", native:"मैथिली", flag:"" },
  { code:"sat", name:"Santali", native:"ᱥᱟᱱᱛᱟᱲᱤ", flag:"" },
  { code:"ks", name:"Kashmiri", native:"کٲشُر", flag:"" },
  { code:"ne", name:"Nepali", native:"नेपाली", flag:"" },
  { code:"sd", name:"Sindhi", native:"سنڌي", flag:"" },
  { code:"kok", name:"Konkani", native:"कोंकणी", flag:"" },
  { code:"doi", name:"Dogri", native:"डोगरी", flag:"" },
  { code:"mni", name:"Manipuri", native:"মণিপুরী", flag:"" },
  { code:"brx", name:"Bodo", native:"बर'", flag:"" },
  { code:"sa", name:"Sanskrit", native:"संस्कृतम्", flag:"" },
];
const en = {
  appName:"ONIONSETU", appSubtitle:"AI-Assisted Grading",
  selectLanguage:"Select Language", selectLanguageDesc:"Choose your preferred language — you can change it anytime in Settings.",
  continue:"Continue", back:"Back", next:"Next", save:"Save", loading:"Loading...", search:"Search", viewAll:"View all", openReport:"Open report", newAssessment:"New Assessment",
  dashboard:"Dashboard", assessments:"Assessments", reviews:"Reviews", reports:"Reports", policy:"Policy", settings:"Settings",
  farmer:"Farmer", grader:"Grader", farmerDesc:"View my lots, reports & QR verification", graderDesc:"Grade lots, human review, policy",
  login:"Login", signup:"Sign up", logout:"Logout", welcomeBack:"Welcome back to", welcomeCreate:"Create your", onionSetu:"OnionSetu",
  gmailOrPhone:"Gmail or Phone number", password:"Password", fullName:"Full name", villageCenter:"Village / Center",
  sendOtp:"Send OTP", verifyOtp:"Verify OTP", resendOtp:"Resend OTP", enterOtp:"Enter 6-digit OTP", demoAccounts:"Demo accounts", quickLogin:"Quick login", noAccount:"No account?", haveAccount:"Already have an account?",
  myAssessments:"My assessments", allAssessments:"All assessments", todaysAssessments:"Today's Assessments", gradeAPercent:"Grade A %", humanReviews:"Human Reviews", pendingDisputes:"On Hold", recentAssessments:"Recent assessments", activity:"Activity", howItWorks:"How it works",
  qualityReports:"Quality reports", reportId:"Report ID", date:"Date", location:"Location", policyVersion:"Policy version", gradeA:"Grade A %", urs:"URS %", confidence:"Confidence", farmerAck:"Farmer acknowledgement", graderAck:"Grader acknowledgement", disputeStatus:"Review status", sampleSize:"Sample size", lotId:"Lot ID", hash:"Hash (SHA-256)", uploadedImages:"Uploaded Images", perOnionResults:"Per-Onion Results",
  downloadInSelected:"Download in", downloadInEnglish:"Download in English", qrVerify:"QR Verification", openVerification:"Open verification",
  gradingPolicy:"Grading policy", sizeBand:"Size band", defectTolerances:"Defect tolerances", offlineSync:"Offline & Sync", system:"System", languageSettings:"Language", changeLanguage:"Change language",
  myFarm:"My farm — grading overview", procOverview:"AI-assisted procurement overview", newAssessmentTitle:"New assessment", farmerGraderSession:"Farmer + Grader joint session · AI assists, human decides",
  storedReportData:"Stored Report Data", finalReport:"Final Report", viewOf:"View", withRef:"with 25mm ref", storedIn:"Stored in Supabase Storage", demoPlaceholder:"Demo placeholder",
  acknowledged:"Acknowledged", accepted:"Accepted", pending:"Pending", noDispute:"On Hold", underReview:"On Hold", disputed:"Rejected", generatePdf:"Generate PDF · Print", markAck:"Mark acknowledged", flagReview:"Flag Report / Second Review",
  verification:"Verification", reportVerified:"Report Verified", lotStatus:"Lot Status",
  stepLotInfo:"Lot Info", stepSampling:"Sampling", stepCapture:"Capture", stepQualityGate:"Quality Gate", stepDetection:"Detection", stepSize:"Size", stepDefects:"Defects", stepConfidence:"Confidence", stepHumanReview:"Human Review", stepPolicyGrading:"Policy & Grading", stepFarmerReview:"Farmer Review", stepReportEvidence:"Report & Evidence",
  lotInformation:"Lot Information", representativeSampling:"Representative Sampling", multiViewCapture:"Multi-View Capture", imageQualityGate:"Image Quality Gate", onionDetection:"Onion Detection / Segmentation", sizeAnalysis:"Size Analysis", defectAnalysis:"Defect Analysis", confidenceGate:"Confidence Gate", humanReviewTitle:"Human Review", versionedPolicy:"Versioned Policy & Grading", farmerGraderReview:"Farmer / Grader Review", qualityReportEvidence:"Quality Report · Evidence · Sync",
  captureGuidance:"Capture guidance", evenLighting:"Even lighting", includeRef:"Include 25 mm reference in View 1", fillFrame:"Fill frame — avoid overlap", onionsVisible:"Onions fully visible",
  procCenter:"Procurement Center", assessor:"Assessor (Grader)",
};
function f(t){ return { ...en, ...t }; }
const dict = {
  en,
  hi: f({ selectLanguage:"भाषा चुनें", selectLanguageDesc:"अपनी पसंदीदा भाषा चुनें — आप इसे सेटिंग्स में कभी भी बदल सकते हैं।", continue:"जारी रखें", back:"पीछे", next:"आगे", save:"सहेजें", loading:"लोड हो रहा है...", search:"खोजें", viewAll:"सभी देखें", openReport:"रिपोर्ट खोलें", newAssessment:"नया मूल्यांकन", dashboard:"डैशबोर्ड", assessments:"मूल्यांकन", reviews:"समीक्षा", reports:"रिपोर्ट", policy:"नीति", settings:"सेटिंग्स", farmer:"किसान", grader:"ग्रेडर", farmerDesc:"मेरे लॉट, रिपोर्ट और QR सत्यापन देखें", graderDesc:"लॉट ग्रेड करें, समीक्षा, नीति", login:"लॉगिन", signup:"साइन अप", logout:"लॉगआउट", welcomeBack:"वापसी पर स्वागत है", welcomeCreate:"अपना बनाएं", onionSetu:"ओनियनसेतु", gmailOrPhone:"जीमेल या फोन नंबर", password:"पासवर्ड", fullName:"पूरा नाम", villageCenter:"गाँव / केंद्र", sendOtp:"OTP भेजें", verifyOtp:"OTP सत्यापित करें", resendOtp:"OTP पुनः भेजें", enterOtp:"6-अंकों का OTP दर्ज करें", demoAccounts:"डेमो खाते", quickLogin:"त्वरित लॉगिन", noAccount:"खाता नहीं है?", haveAccount:"पहले से खाता है?", myAssessments:"मेरे मूल्यांकन", allAssessments:"सभी मूल्यांकन", todaysAssessments:"आज के मूल्यांकन", gradeAPercent:"ग्रेड A %", humanReviews:"मानव समीक्षा", pendingDisputes:"लंबित विवाद", recentAssessments:"हाल के मूल्यांकन", activity:"गतिविधि", howItWorks:"कैसे काम करता है", qualityReports:"गुणवत्ता रिपोर्ट", reportId:"रिपोर्ट आईडी", date:"तारीख", location:"स्थान", policyVersion:"नीति संस्करण", gradeA:"ग्रेड A %", urs:"URS %", confidence:"विश्वास", farmerAck:"किसान स्वीकृति", graderAck:"ग्रेडर स्वीकृति", disputeStatus:"समीक्षा स्थिति", sampleSize:"नमूना आकार", lotId:"लॉट आईडी", hash:"हैश", uploadedImages:"अपलोड की गई तस्वीरें", perOnionResults:"प्रति प्याज परिणाम", downloadInSelected:"डाउनलोड करें", downloadInEnglish:"अंग्रेजी में डाउनलोड", qrVerify:"QR सत्यापन", openVerification:"सत्यापन खोलें", gradingPolicy:"ग्रेडिंग नीति", sizeBand:"आकार सीमा", defectTolerances:"दोष सहनशीलता", offlineSync:"ऑफलाइन और सिंक", system:"सिस्टम", languageSettings:"भाषा", changeLanguage:"भाषा बदलें", myFarm:"मेरा खेत — ग्रेडिंग अवलोकन", procOverview:"AI-सहायित खरीद अवलोकन", newAssessmentTitle:"नया मूल्यांकन", farmerGraderSession:"किसान + ग्रेडर संयुक्त सत्र", storedReportData:"संग्रहीत रिपोर्ट डेटा", finalReport:"अंतिम रिपोर्ट", acknowledged:"स्वीकृत ", accepted:"स्वीकृत", pending:"लंबित", noDispute:"कोई विवाद नहीं", underReview:"समीक्षाधीन", disputed:"विवादित", generatePdf:"PDF बनाएं · प्रिंट", markAck:"स्वीकृति दर्ज करें", flagReview:"रिपोर्ट फ्लैग करें", verification:"सत्यापन", reportVerified:"रिपोर्ट सत्यापित",
    stepLotInfo:"लॉट जानकारी", stepSampling:"नमूना चयन", stepCapture:"कैप्चर", stepQualityGate:"गुणवत्ता जाँच", stepDetection:"पहचान", stepSize:"आकार", stepDefects:"दोष", stepConfidence:"विश्वास", stepHumanReview:"मानव समीक्षा", stepPolicyGrading:"नीति और ग्रेडिंग", stepFarmerReview:"किसान समीक्षा", stepReportEvidence:"रिपोर्ट और साक्ष्य",
    lotInformation:"लॉट जानकारी", representativeSampling:"प्रतिनिधि नमूना", multiViewCapture:"बहु-दृश्य कैप्चर", imageQualityGate:"छवि गुणवत्ता जाँच", onionDetection:"प्याज पहचान / विभाजन", sizeAnalysis:"आकार विश्लेषण", defectAnalysis:"दोष विश्लेषण", confidenceGate:"विश्वास द्वार", humanReviewTitle:"मानव समीक्षा", versionedPolicy:"संस्करणित नीति और ग्रेडिंग", farmerGraderReview:"किसान / ग्रेडर समीक्षा", qualityReportEvidence:"गुणवत्ता रिपोर्ट · साक्ष्य · सिंक",
    captureGuidance:"कैप्चर मार्गदर्शन", evenLighting:"समान प्रकाश", includeRef:"व्यू 1 में 25 मिमी संदर्भ शामिल करें", fillFrame:"फ्रेम भरें — ओवरलैप से बचें", onionsVisible:"प्याज पूरी तरह दिखें", procCenter:"खरीद केंद्र", assessor:"मूल्यांकनकर्ता (ग्रेडर)",
  }),
  bn: f({ selectLanguage:"ভাষা নির্বাচন করুন", selectLanguageDesc:"আপনার পছন্দের ভাষা নির্বাচন করুন — সেটিংসে যেকোনো সময় পরিবর্তন করতে পারবেন।", continue:"চালিয়ে যান", back:"পিছনে", next:"পরবর্তী", save:"সংরক্ষণ", loading:"লোড হচ্ছে...", search:"অনুসন্ধান", viewAll:"সব দেখুন", openReport:"রিপোর্ট খুলুন", newAssessment:"নতুন মূল্যায়ন", dashboard:"ড্যাশবোর্ড", assessments:"মূল্যায়ন", reviews:"পর্যালোচনা", reports:"রিপোর্ট", policy:"নীতি", settings:"সেটিংস", farmer:"কৃষক", grader:"গ্রেডার", farmerDesc:"আমার লট, রিপোর্ট ও QR যাচাই", graderDesc:"লট গ্রেড, পর্যালোচনা, নীতি", login:"লগইন", signup:"সাইন আপ", logout:"লগআউট", welcomeBack:"ফিরে স্বাগতম", welcomeCreate:"তৈরি করুন", onionSetu:"ওনিয়নসেতু", gmailOrPhone:"জিমেইল বা ফোন নম্বর", password:"পাসওয়ার্ড", fullName:"পুরো নাম", villageCenter:"গ্রাম / কেন্দ্র", sendOtp:"OTP পাঠান", verifyOtp:"OTP যাচাই করুন", resendOtp:"পুনরায় পাঠান", enterOtp:"৬-সংখ্যার OTP লিখুন", demoAccounts:"ডেমো অ্যাকাউন্ট", quickLogin:"দ্রুত লগইন", noAccount:"অ্যাকাউন্ট নেই?", haveAccount:"অ্যাকাউন্ট আছে?", myAssessments:"আমার মূল্যায়ন", allAssessments:"সব মূল্যায়ন", todaysAssessments:"আজকের মূল্যায়ন", gradeAPercent:"গ্রেড A %", humanReviews:"মানব পর্যালোচনা", pendingDisputes:"মুলতুবি বিরোধ", recentAssessments:"সাম্প্রতিক মূল্যায়ন", activity:"কার্যকলাপ", howItWorks:"কীভাবে কাজ করে", qualityReports:"গুণমান রিপোর্ট", reportId:"রিপোর্ট আইডি", date:"তারিখ", location:"অবস্থান", policyVersion:"নীতি সংস্করণ", gradeA:"গ্রেড A %", urs:"URS %", confidence:"আত্মবিশ্বাস", farmerAck:"কৃষক স্বীকৃতি", graderAck:"গ্রেডার স্বীকৃতি", disputeStatus:"পর্যালোচনার অবস্থা", sampleSize:"নমুনার আকার", lotId:"লট আইডি", hash:"হ্যাশ", uploadedImages:"আপলোড করা ছবি", perOnionResults:"প্রতি পেঁয়াজ ফলাফল", downloadInSelected:"ডাউনলোড করুন", downloadInEnglish:"ইংরেজিতে ডাউনলোড", qrVerify:"QR যাচাই", openVerification:"যাচাই খুলুন", gradingPolicy:"গ্রেডিং নীতি", sizeBand:"আকার সীমা", defectTolerances:"ত্রুটি সহনশীলতা", offlineSync:"অফলাইন ও সিঙ্ক", system:"সিস্টেম", languageSettings:"ভাষা", changeLanguage:"ভাষা পরিবর্তন", myFarm:"আমার খামার — গ্রেডিং", procOverview:"AI-সহায়িত সংগ্রহ", newAssessmentTitle:"নতুন মূল্যায়ন", farmerGraderSession:"কৃষক + গ্রেডার যৌথ সেশন", storedReportData:"সংরক্ষিত রিপোর্ট", finalReport:"চূড়ান্ত রিপোর্ট", acknowledged:"স্বীকৃত ", pending:"মুলতুবি", noDispute:"কোনো বিরোধ নেই", underReview:"পর্যালোচনাধীন", disputed:"বিরোধপূর্ণ", generatePdf:"PDF তৈরি · প্রিন্ট", markAck:"স্বীকৃতি দিন", flagReview:"রিপোর্ট ফ্ল্যাগ", verification:"যাচাইকরণ", reportVerified:"রিপোর্ট যাচাইকৃত", }),
  te: f({ selectLanguage:"భాషను ఎంచుకోండి", selectLanguageDesc:"మీకు ఇష్టమైన భాషను ఎంచుకోండి — సెట్టింగ్‌లలో ఎప్పుడైనా మార్చవచ్చు.", continue:"కొనసాగించు", back:"వెనుకకు", next:"తదుపరి", save:"సేవ్", loading:"లోడ్ అవుతోంది...", search:"వెతుకు", viewAll:"అన్నీ చూడు", openReport:"నివేదిక తెరువు", newAssessment:"కొత్త మూల్యాంకనం", dashboard:"డాష్‌బోర్డ్", assessments:"మూల్యాంకనాలు", reviews:"సమీక్షలు", reports:"నివేదికలు", policy:"విధానం", settings:"సెట్టింగ్‌లు", farmer:"రైతు", grader:"గ్రేడర్", farmerDesc:"నా లాట్‌లు, నివేదికలు & QR ధృవీకరణ", graderDesc:"లాట్‌లను గ్రేడ్ చేయి, సమీక్ష, విధానం", login:"లాగిన్", signup:"సైన్ అప్", logout:"లాగ్అవుట్", welcomeBack:"తిరిగి స్వాగతం", welcomeCreate:"సృష్టించు", onionSetu:"ఆనియన్‌సేతు", gmailOrPhone:"జీమెయిల్ లేదా ఫోన్", password:"పాస్‌వర్డ్", fullName:"పూర్తి పేరు", villageCenter:"గ్రామం / కేంద్రం", sendOtp:"OTP పంపండి", verifyOtp:"OTP ధృవీకరించు", resendOtp:"మళ్లీ పంపు", enterOtp:"6-అంకెల OTP నమోదు చేయండి", demoAccounts:"డెమో ఖాతాలు", quickLogin:"త్వరిత లాగిన్", noAccount:"ఖాతా లేదా?", haveAccount:"ఖాతా ఉందా?", myAssessments:"నా మూల్యాంకనాలు", allAssessments:"అన్ని మూల్యాంకనాలు", todaysAssessments:"నేటి మూల్యాంకనాలు", gradeAPercent:"గ్రేడ్ A %", humanReviews:"మానవ సమీక్షలు", pendingDisputes:"పెండింగ్ వివాదాలు", recentAssessments:"ఇటీవలి మూల్యాంకనాలు", activity:"కార్యాచరణ", howItWorks:"ఎలా పనిచేస్తుంది", qualityReports:"నాణ్యత నివేదికలు", reportId:"నివేదిక ఐడి", date:"తేదీ", location:"ప్రదేశం", policyVersion:"విధాన సంస్కరణ", gradeA:"గ్రేడ్ A %", urs:"URS %", confidence:"నమ్మకం", farmerAck:"రైతు ఆమోదం", graderAck:"గ్రేడర్ ఆమోదం", disputeStatus:"సమీక్ష స్థితి", sampleSize:"నమూనా పరిమాణం", lotId:"లాట్ ఐడి", hash:"హ్యాష్", uploadedImages:"అప్‌లోడ్ చేసిన చిత్రాలు", perOnionResults:"ఉల్లిపాయ వారీ ఫలితాలు", downloadInSelected:"డౌన్‌లోడ్", downloadInEnglish:"ఇంగ్లీష్‌లో డౌన్‌లోడ్", qrVerify:"QR ధృవీకరణ", openVerification:"ధృవీకరణ తెరువు", gradingPolicy:"గ్రేడింగ్ విధానం", sizeBand:"పరిమాణ పరిధి", defectTolerances:"లోప సహనం", offlineSync:"ఆఫ్‌లైన్ & సింక్", system:"వ్యవస్థ", languageSettings:"భాష", changeLanguage:"భాష మార్చు", myFarm:"నా పొలం — గ్రేడింగ్", procOverview:"AI-సహాయిత సేకరణ", newAssessmentTitle:"కొత్త మూల్యాంకనం", farmerGraderSession:"రైతు + గ్రేడర్ ఉమ్మడి సెషన్", storedReportData:"నిల్వ చేసిన నివేదిక", finalReport:"తుది నివేదిక", acknowledged:"ఆమోదించబడింది ", pending:"పెండింగ్", noDispute:"వివాదం లేదు", underReview:"సమీక్షలో", disputed:"వివాదాస్పద", generatePdf:"PDF సృష్టించు · ప్రింట్", markAck:"ఆమోదించు", flagReview:"నివేదికను ఫ్లాగ్ చేయి", verification:"ధృవీకరణ", reportVerified:"నివేదిక ధృవీకరించబడింది", }),
  mr: f({ selectLanguage:"भाषा निवडा", selectLanguageDesc:"तुमची आवडती भाषा निवडा — सेटिंग्जमध्ये कधीही बदलू शकता.", continue:"पुढे जा", back:"मागे", next:"पुढील", save:"जतन करा", loading:"लोड होत आहे...", search:"शोधा", viewAll:"सर्व पहा", openReport:"अहवाल उघडा", newAssessment:"नवीन मूल्यमापन", dashboard:"डॅशबोर्ड", assessments:"मूल्यमापन", reviews:"पुनरावलोकन", reports:"अहवाल", policy:"धोरण", settings:"सेटिंग्ज", farmer:"शेतकरी", grader:"ग्रेडर", farmerDesc:"माझे लॉट, अहवाल व QR पडताळणी", graderDesc:"लॉट ग्रेड करा, पुनरावलोकन, धोरण", login:"लॉगिन", signup:"साइन अप", logout:"लॉगआउट", welcomeBack:"परत स्वागत आहे", welcomeCreate:"तयार करा", onionSetu:"ओनियनसेतू", gmailOrPhone:"जीमेल किंवा फोन", password:"पासवर्ड", fullName:"पूर्ण नाव", villageCenter:"गाव / केंद्र", sendOtp:"OTP पाठवा", verifyOtp:"OTP पडताळा", resendOtp:"पुन्हा पाठवा", enterOtp:"6-अंकी OTP टाका", demoAccounts:"डेमो खाती", quickLogin:"त्वरित लॉगिन", noAccount:"खाते नाही?", haveAccount:"खाते आहे?", myAssessments:"माझे मूल्यमापन", allAssessments:"सर्व मूल्यमापन", todaysAssessments:"आजचे मूल्यमापन", gradeAPercent:"ग्रेड A %", humanReviews:"मानवी पुनरावलोकन", pendingDisputes:"प्रलंबित वाद", recentAssessments:"अलीकडील मूल्यमापन", activity:"हालचाली", howItWorks:"कसे कार्य करते", qualityReports:"गुणवत्ता अहवाल", reportId:"अहवाल आयडी", date:"तारीख", location:"स्थान", policyVersion:"धोरण आवृत्ती", gradeA:"ग्रेड A %", urs:"URS %", confidence:"विश्वास", farmerAck:"शेतकरी मान्यता", graderAck:"ग्रेडर मान्यता", disputeStatus:"पुनरावलोकन स्थिती", sampleSize:"नमुना आकार", lotId:"लॉट आयडी", hash:"हॅश", uploadedImages:"अपलोड केलेल्या प्रतिमा", perOnionResults:"प्रति कांदा निकाल", downloadInSelected:"डाउनलोड करा", downloadInEnglish:"इंग्रजीत डाउनलोड", qrVerify:"QR पडताळणी", openVerification:"पडताळणी उघडा", gradingPolicy:"ग्रेडिंग धोरण", sizeBand:"आकार श्रेणी", defectTolerances:"दोष सहनशीलता", offlineSync:"ऑफलाइन व सिंक", system:"प्रणाली", languageSettings:"भाषा", changeLanguage:"भाषा बदला", myFarm:"माझे शेत — ग्रेडिंग", procOverview:"AI-सहाय्यक खरेदी", newAssessmentTitle:"नवीन मूल्यमापन", farmerGraderSession:"शेतकरी + ग्रेडर संयुक्त सत्र", storedReportData:"जतन केलेला अहवाल", finalReport:"अंतिम अहवाल", acknowledged:"मान्य ", pending:"प्रलंबित", noDispute:"वाद नाही", underReview:"पुनरावलोकनात", disputed:"वादग्रस्त", generatePdf:"PDF तयार करा · प्रिंट", markAck:"मान्यता द्या", flagReview:"अहवाल फ्लॅग करा", verification:"पडताळणी", reportVerified:"अहवाल पडताळला", }),
  ta: f({ selectLanguage:"மொழியைத் தேர்ந்தெடுக்கவும்", selectLanguageDesc:"உங்களுக்கு பிடித்த மொழியைத் தேர்ந்தெடுக்கவும் — அமைப்புகளில் எப்போதும் மாற்றலாம்.", continue:"தொடரவும்", back:"பின்", next:"அடுத்து", save:"சேமி", loading:"ஏற்றுகிறது...", search:"தேடு", viewAll:"அனைத்தும் காண்க", openReport:"அறிக்கை திற", newAssessment:"புதிய மதிப்பீடு", dashboard:"டாஷ்போர்டு", assessments:"மதிப்பீடுகள்", reviews:"மறுஆய்வுகள்", reports:"அறிக்கைகள்", policy:"கொள்கை", settings:"அமைப்புகள்", farmer:"விவசாயி", grader:"தரநிர்ணயிப்பாளர்", farmerDesc:"என் லாட்கள், அறிக்கைகள் & QR சரிபார்ப்பு", graderDesc:"லாட்களை தரப்படுத்து, மறுஆய்வு, கொள்கை", login:"உள்நுழை", signup:"பதிவு", logout:"வெளியேறு", welcomeBack:"மீண்டும் வரவேற்கிறோம்", welcomeCreate:"உருவாக்கு", onionSetu:"ஆனியன்சேது", gmailOrPhone:"ஜிமெயில் அல்லது தொலைபேசி", password:"கடவுச்சொல்", fullName:"முழு பெயர்", villageCenter:"கிராமம் / மையம்", sendOtp:"OTP அனுப்பு", verifyOtp:"OTP சரிபார்", resendOtp:"மீண்டும் அனுப்பு", enterOtp:"6-இலக்க OTP உள்ளிடுக", demoAccounts:"டெமோ கணக்குகள்", quickLogin:"விரைவு உள்நுழைவு", noAccount:"கணக்கு இல்லையா?", haveAccount:"கணக்கு உள்ளதா?", myAssessments:"என் மதிப்பீடுகள்", allAssessments:"அனைத்து மதிப்பீடுகள்", todaysAssessments:"இன்றைய மதிப்பீடுகள்", gradeAPercent:"கிரேடு A %", humanReviews:"மனித மதிப்பாய்வுகள்", pendingDisputes:"நிலுவை சர்ச்சைகள்", recentAssessments:"சமீபத்திய மதிப்பீடுகள்", activity:"செயல்பாடு", howItWorks:"எப்படி வேலை செய்கிறது", qualityReports:"தர அறிக்கைகள்", reportId:"அறிக்கை ஐடி", date:"தேதி", location:"இடம்", policyVersion:"கொள்கை பதிப்பு", gradeA:"கிரேடு A %", urs:"URS %", confidence:"நம்பிக்கை", farmerAck:"விவசாயி ஒப்புதல்", graderAck:"தரநிர்ணயிப்பாளர் ஒப்புதல்", disputeStatus:"மதிப்பாய்வு நிலை", sampleSize:"மாதிரி அளவு", lotId:"லாட் ஐடி", hash:"ஹாஷ்", uploadedImages:"பதிவேற்றிய படங்கள்", perOnionResults:"வெங்காய வாரியாக முடிவுகள்", downloadInSelected:"பதிவிறக்கு", downloadInEnglish:"ஆங்கிலத்தில் பதிவிறக்க", qrVerify:"QR சரிபார்ப்பு", openVerification:"சரிபார்ப்பு திற", gradingPolicy:"தரக் கொள்கை", sizeBand:"அளவு பட்டை", defectTolerances:"குறைபாடு பொறுமை", offlineSync:"ஆஃப்லைன் & ஒத்திசைவு", system:"அமைப்பு", languageSettings:"மொழி", changeLanguage:"மொழி மாற்று", myFarm:"என் பண்ணை — தரம்", procOverview:"AI உதவி கொள்முதல்", newAssessmentTitle:"புதிய மதிப்பீடு", farmerGraderSession:"விவசாயி + தரநிர்ணயிப்பாளர் கூட்டு", storedReportData:"சேமித்த அறிக்கை", finalReport:"இறுதி அறிக்கை", acknowledged:"ஒப்புக்கொள்ளப்பட்டது ", pending:"நிலுவை", noDispute:"சர்ச்சை இல்லை", underReview:"மதிப்பாய்வில்", disputed:"சர்ச்சைக்குரிய", generatePdf:"PDF உருவாக்கு · அச்சிடு", markAck:"ஒப்புதல் குறி", flagReview:"அறிக்கையைக் கொடியிடு", verification:"சரிபார்ப்பு", reportVerified:"அறிக்கை சரிபார்க்கப்பட்டது", }),
  gu: f({ selectLanguage:"ભાષા પસંદ કરો", selectLanguageDesc:"તમારી પસંદગીની ભાષા પસંદ કરો — સેટિંગ્સમાં ક્યારેય પણ બદલી શકો છો.", continue:"ચાલુ રાખો", back:"પાછળ", next:"આગળ", save:"સાચવો", loading:"લોડ થઈ રહ્યું છે...", search:"શોધો", viewAll:"બધું જુઓ", openReport:"રિપોર્ટ ખોલો", newAssessment:"નવું મૂલ્યાંકન", dashboard:"ડેશબોર્ડ", assessments:"મૂલ્યાંકન", reviews:"સમીક્ષા", reports:"રિપોર્ટ", policy:"નીતિ", settings:"સેટિંગ્સ", farmer:"ખેડૂત", grader:"ગ્રેડર", farmerDesc:"મારા લોટ, રિપોર્ટ અને QR ચકાસણી", graderDesc:"લોટ ગ્રેડ કરો, સમીક્ષા, નીતિ", login:"લોગિન", signup:"સાઇન અપ", logout:"લોગઆઉટ", welcomeBack:"ફરી સ્વાગત છે", welcomeCreate:"બનાવો", onionSetu:"ઓનિયનસેતુ", gmailOrPhone:"જીમેઇલ અથવા ફોન", password:"પાસવર્ડ", fullName:"પૂરું નામ", villageCenter:"ગામ / કેન્દ્ર", sendOtp:"OTP મોકલો", verifyOtp:"OTP ચકાસો", resendOtp:"ફરી મોકલો", enterOtp:"6-અંકનો OTP દાખલ કરો", demoAccounts:"ડેમો ખાતા", quickLogin:"ઝડપી લોગિન", noAccount:"ખાતું નથી?", haveAccount:"ખાતું છે?", myAssessments:"મારા મૂલ્યાંકન", allAssessments:"બધા મૂલ્યાંકન", todaysAssessments:"આજના મૂલ્યાંકન", gradeAPercent:"ગ્રેડ A %", humanReviews:"માનવ સમીક્ષા", pendingDisputes:"બાકી વિવાદ", recentAssessments:"તાજેતરના મૂલ્યાંકન", activity:"પ્રવૃત્તિ", howItWorks:"કેવી રીતે કામ કરે", qualityReports:"ગુણવત્તા રિપોર્ટ", reportId:"રિપોર્ટ આઈડી", date:"તારીખ", location:"સ્થાન", policyVersion:"નીતિ સંસ્કરણ", gradeA:"ગ્રેડ A %", urs:"URS %", confidence:"વિશ્વાસ", farmerAck:"ખેડૂત સ્વીકૃતિ", graderAck:"ગ્રેડર સ્વીકૃતિ", disputeStatus:"સમીક્ષા સ્થિતિ", sampleSize:"નમૂના કદ", lotId:"લોટ આઈડી", hash:"હેશ", uploadedImages:"અપલોડ કરેલી છબીઓ", perOnionResults:"પ્રતિ ડુંગળી પરિણામ", downloadInSelected:"ડાઉનલોડ કરો", downloadInEnglish:"અંગ્રેજીમાં ડાઉનલોડ", qrVerify:"QR ચકાસણી", openVerification:"ચકાસણી ખોલો", gradingPolicy:"ગ્રેડિંગ નીતિ", sizeBand:"કદ શ્રેણી", defectTolerances:"ખામી સહનશીલતા", offlineSync:"ઑફલાઇન અને સિંક", system:"સિસ્ટમ", languageSettings:"ભાષા", changeLanguage:"ભાષા બદલો", myFarm:"મારું ખેતર — ગ્રેડિંગ", procOverview:"AI-સહાયિત ખરીદી", newAssessmentTitle:"નવું મૂલ્યાંકન", farmerGraderSession:"ખેડૂત + ગ્રેડર સંયુક્ત", storedReportData:"સંગ્રહિત રિપોર્ટ", finalReport:"અંતિમ રિપોર્ટ", acknowledged:"સ્વીકૃત ", pending:"બાકી", noDispute:"કોઈ વિવાદ નથી", underReview:"સમીક્ષા હેઠળ", disputed:"વિવાદિત", generatePdf:"PDF બનાવો · પ્રિન્ટ", markAck:"સ્વીકૃતિ આપો", flagReview:"રિપોર્ટ ફ્લેગ કરો", verification:"ચકાસણી", reportVerified:"રિપોર્ટ ચકાસાયેલ", }),
  ur: f({ selectLanguage:"زبان منتخب کریں", selectLanguageDesc:"اپنی پسندیدہ زبان منتخب کریں — سیٹنگز میں کسی بھی وقت تبدیل کر سکتے ہیں۔", continue:"جاری رکھیں", back:"پیچھے", next:"اگلا", save:"محفوظ کریں", loading:"لوڈ ہو رہا ہے...", search:"تلاش", viewAll:"سب دیکھیں", openReport:"رپورٹ کھولیں", newAssessment:"نئی تشخیص", dashboard:"ڈیش بورڈ", assessments:"تشخیص", reviews:"جائزہ", reports:"رپورٹس", policy:"پالیسی", settings:"ترتیبات", farmer:"کسان", grader:"گریڈر", farmerDesc:"میرے لاٹ، رپورٹس اور QR تصدیق", graderDesc:"لاٹ گریڈ، جائزہ، پالیسی", login:"لاگ ان", signup:"سائن اپ", logout:"لاگ آؤٹ", welcomeBack:"خوش آمدید", welcomeCreate:"بنائیں", onionSetu:"اونیئن سیتو", gmailOrPhone:"جیمیل یا فون", password:"پاس ورڈ", fullName:"پورا نام", villageCenter:"گاؤں / مرکز", sendOtp:"OTP بھیجیں", verifyOtp:"OTP کی تصدیق", resendOtp:"دوبارہ بھیجیں", enterOtp:"6-ہندسی OTP درج کریں", demoAccounts:"ڈیمو اکاؤنٹس", quickLogin:"فوری لاگ ان", noAccount:"اکاؤنٹ نہیں؟", haveAccount:"اکاؤنٹ ہے؟", myAssessments:"میری تشخیص", allAssessments:"تمام تشخیص", todaysAssessments:"آج کی تشخیص", gradeAPercent:"گریڈ A %", humanReviews:"انسانی جائزے", pendingDisputes:"زیر التوا تنازعات", recentAssessments:"حالیہ تشخیص", activity:"سرگرمی", howItWorks:"کیسے کام کرتا ہے", qualityReports:"معیار رپورٹس", reportId:"رپورٹ آئی ڈی", date:"تاریخ", location:"مقام", policyVersion:"پالیسی ورژن", gradeA:"گریڈ A %", urs:"URS %", confidence:"اعتماد", farmerAck:"کسان کی توثیق", graderAck:"گریڈر کی توثیق", disputeStatus:"جائزہ کی حیثیت", sampleSize:"نمونہ سائز", lotId:"لاٹ آئی ڈی", hash:"ہیش", uploadedImages:"اپ لوڈ کردہ تصاویر", perOnionResults:"فی پیاز نتائج", downloadInSelected:"ڈاؤن لوڈ", downloadInEnglish:"انگریزی میں ڈاؤن لوڈ", qrVerify:"QR تصدیق", openVerification:"تصدیق کھولیں", gradingPolicy:"گریڈنگ پالیسی", sizeBand:"سائز بینڈ", defectTolerances:"خرابی برداشت", offlineSync:"آف لائن اور سنک", system:"سسٹم", languageSettings:"زبان", changeLanguage:"زبان بدلیں", myFarm:"میرا فارم — گریڈنگ", procOverview:"AI سے مدد یافتہ خریداری", newAssessmentTitle:"نئی تشخیص", farmerGraderSession:"کسان + گریڈر مشترکہ", storedReportData:"محفوظ شدہ رپورٹ", finalReport:"حتمی رپورٹ", acknowledged:"تصدیق شدہ ", pending:"زیر التوا", noDispute:"کوئی تنازعہ نہیں", underReview:"جائزہ میں", disputed:"متنازعہ", generatePdf:"PDF بنائیں · پرنٹ", markAck:"توثیق کریں", flagReview:"رپورٹ فلیگ", verification:"تصدیق", reportVerified:"رپورٹ کی تصدیق", }),
  kn: f({ selectLanguage:"ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", selectLanguageDesc:"ನಿಮ್ಮ ನೆಚ್ಚಿನ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ — ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.", continue:"ಮುಂದುವರಿಸಿ", back:"ಹಿಂದೆ", next:"ಮುಂದೆ", save:"ಉಳಿಸಿ", loading:"ಲೋಡ್ ಆಗುತ್ತಿದೆ...", search:"ಹುಡುಕಿ", viewAll:"ಎಲ್ಲಾ ನೋಡಿ", openReport:"ವರದಿ ತೆರೆಯಿರಿ", newAssessment:"ಹೊಸ ಮೌಲ್ಯಮಾಪನ", dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", assessments:"ಮೌಲ್ಯಮಾಪನ", reviews:"ವಿಮರ್ಶೆ", reports:"ವರದಿಗಳು", policy:"ನೀತಿ", settings:"ಸೆಟ್ಟಿಂಗ್‌ಗಳು", farmer:"ರೈತ", grader:"ಗ್ರೇಡರ್", farmerDesc:"ನನ್ನ ಲಾಟ್‌ಗಳು, ವರದಿಗಳು & QR ಪರಿಶೀಲನೆ", graderDesc:"ಲಾಟ್‌ಗಳನ್ನು ಗ್ರೇಡ್ ಮಾಡಿ, ವಿಮರ್ಶೆ, ನೀತಿ", login:"ಲಾಗಿನ್", signup:"ಸೈನ್ ಅಪ್", logout:"ಲಾಗ್ಔಟ್", welcomeBack:"ಮರಳಿ ಸ್ವಾಗತ", welcomeCreate:"ರಚಿಸಿ", onionSetu:"ಈರುಳ್ಳಿ ಸೇತು", gmailOrPhone:"ಜಿಮೇಲ್ ಅಥವಾ ಫೋನ್", password:"ಪಾಸ್‌ವರ್ಡ್", fullName:"ಪೂರ್ಣ ಹೆಸರು", villageCenter:"ಗ್ರಾಮ / ಕೇಂದ್ರ", sendOtp:"OTP ಕಳುಹಿಸಿ", verifyOtp:"OTP ಪರಿಶೀಲಿಸಿ", resendOtp:"ಮತ್ತೆ ಕಳುಹಿಸಿ", enterOtp:"6-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ", demoAccounts:"ಡೆಮೊ ಖಾತೆಗಳು", quickLogin:"ತ್ವರಿತ ಲಾಗಿನ್", noAccount:"ಖಾತೆ ಇಲ್ಲವೇ?", haveAccount:"ಖಾತೆ ಇದೆಯೇ?", myAssessments:"ನನ್ನ ಮೌಲ್ಯಮಾಪನ", allAssessments:"ಎಲ್ಲಾ ಮೌಲ್ಯಮಾಪನ", todaysAssessments:"ಇಂದಿನ ಮೌಲ್ಯಮಾಪನ", gradeAPercent:"ಗ್ರೇಡ್ A %", humanReviews:"ಮಾನವ ವಿಮರ್ಶೆಗಳು", pendingDisputes:"ಬಾಕಿ ವಿವಾದಗಳು", recentAssessments:"ಇತ್ತೀಚಿನ ಮೌಲ್ಯಮಾಪನ", activity:"ಚಟುವಟಿಕೆ", howItWorks:"ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", qualityReports:"ಗುಣಮಟ್ಟ ವರದಿಗಳು", reportId:"ವರದಿ ಐಡಿ", date:"ದಿನಾಂಕ", location:"ಸ್ಥಳ", policyVersion:"ನೀತಿ ಆವೃತ್ತಿ", gradeA:"ಗ್ರೇಡ್ A %", urs:"URS %", confidence:"ವಿಶ್ವಾಸ", farmerAck:"ರೈತ ಒಪ್ಪಿಗೆ", graderAck:"ಗ್ರೇಡರ್ ಒಪ್ಪಿಗೆ", disputeStatus:"ವಿಮರ್ಶೆ ಸ್ಥಿತಿ", sampleSize:"ಮಾದರಿ ಗಾತ್ರ", lotId:"ಲಾಟ್ ಐಡಿ", hash:"ಹ್ಯಾಶ್", uploadedImages:"ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಚಿತ್ರಗಳು", perOnionResults:"ಪ್ರತಿ ಈರುಳ್ಳಿ ಫಲಿತಾಂಶ", downloadInSelected:"ಡೌನ್‌ಲೋಡ್", downloadInEnglish:"ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಡೌನ್‌ಲೋಡ್", qrVerify:"QR ಪರಿಶೀಲನೆ", openVerification:"ಪರಿಶೀಲನೆ ತೆರೆಯಿರಿ", gradingPolicy:"ಗ್ರೇಡಿಂಗ್ ನೀತಿ", sizeBand:"ಗಾತ್ರದ ಪಟ್ಟಿ", defectTolerances:"ದೋಷ ಸಹಿಷ್ಣುತೆ", offlineSync:"ಆಫ್‌ಲೈನ್ & ಸಿಂಕ್", system:"ವ್ಯವಸ್ಥೆ", languageSettings:"ಭಾಷೆ", changeLanguage:"ಭಾಷೆ ಬದಲಾಯಿಸಿ", myFarm:"ನನ್ನ ಹೊಲ — ಗ್ರೇಡಿಂಗ್", procOverview:"AI-ಸಹಾಯಿತ ಖರೀದಿ", newAssessmentTitle:"ಹೊಸ ಮೌಲ್ಯಮಾಪನ", farmerGraderSession:"ರೈತ + ಗ್ರೇಡರ್ ಜಂಟಿ", storedReportData:"ಸಂಗ್ರಹಿಸಿದ ವರದಿ", finalReport:"ಅಂತಿಮ ವರದಿ", acknowledged:"ಒಪ್ಪಲಾಗಿದೆ ", pending:"ಬಾಕಿ", noDispute:"ವಿವಾದವಿಲ್ಲ", underReview:"ಪರಿಶೀಲನೆಯಲ್ಲಿ", disputed:"ವಿವಾದಿತ", generatePdf:"PDF ರಚಿಸಿ · ಮುದ್ರಿಸಿ", markAck:"ಒಪ್ಪಿಗೆ ನೀಡಿ", flagReview:"ವರದಿಯನ್ನು ಫ್ಲ್ಯಾಗ್ ಮಾಡಿ", verification:"ಪರಿಶೀಲನೆ", reportVerified:"ವರದಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ", }),
  ml: f({ selectLanguage:"ഭാഷ തിരഞ്ഞെടുക്കുക", selectLanguageDesc:"നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക — ക്രമീകരണങ്ങളിൽ എപ്പോഴും മാറ്റാം.", continue:"തുടരുക", back:"പിന്നോട്ട്", next:"അടുത്തത്", save:"സംരക്ഷിക്കുക", loading:"ലോഡ് ചെയ്യുന്നു...", search:"തിരയുക", viewAll:"എല്ലാം കാണുക", openReport:"റിപ്പോർട്ട് തുറക്കുക", newAssessment:"പുതിയ മൂല്യനിർണയം", dashboard:"ഡാഷ്‌ബോർഡ്", assessments:"മൂല്യനിർണയം", reviews:"അവലോകനം", reports:"റിപ്പോർട്ടുകൾ", policy:"നയം", settings:"ക്രമീകരണങ്ങൾ", farmer:"കർഷകൻ", grader:"ഗ്രേഡർ", farmerDesc:"എന്റെ ലോട്ടുകൾ, റിപ്പോർട്ടുകൾ & QR പരിശോധന", graderDesc:"ലോട്ടുകൾ ഗ്രേഡ് ചെയ്യുക, അവലോകനം, നയം", login:"ലോഗിൻ", signup:"സൈൻ അപ്പ്", logout:"ലോഗൗട്ട്", welcomeBack:"തിരികെ സ്വാഗതം", welcomeCreate:"സൃഷ്ടിക്കുക", onionSetu:"ഒണിയൻസേതു", gmailOrPhone:"ജിമെയിൽ അല്ലെങ്കിൽ ഫോൺ", password:"പാസ്‌വേഡ്", fullName:"പൂർണ്ണ പേര്", villageCenter:"ഗ്രാമം / കേന്ദ്രം", sendOtp:"OTP അയയ്ക്കുക", verifyOtp:"OTP പരിശോധിക്കുക", resendOtp:"വീണ്ടും അയയ്ക്കുക", enterOtp:"6-അക്ക OTP നൽകുക", demoAccounts:"ഡെമോ അക്കൗണ്ടുകൾ", quickLogin:"ദ്രുത ലോഗിൻ", noAccount:"അക്കൗണ്ട് ഇല്ലേ?", haveAccount:"അക്കൗണ്ട് ഉണ്ടോ?", myAssessments:"എന്റെ മൂല്യനിർണയങ്ങൾ", allAssessments:"എല്ലാ മൂല്യനിർണയങ്ങൾ", todaysAssessments:"ഇന്നത്തെ മൂല്യനിർണയങ്ങൾ", gradeAPercent:"ഗ്രേഡ് A %", humanReviews:"മാനുഷിക അവലോകനങ്ങൾ", pendingDisputes:"തീർപ്പാക്കാത്ത തർക്കങ്ങൾ", recentAssessments:"സമീപകാല മൂല്യനിർണയങ്ങൾ", activity:"പ്രവർത്തനം", howItWorks:"എങ്ങനെ പ്രവർത്തിക്കുന്നു", qualityReports:"ഗുണനിലവാര റിപ്പോർട്ടുകൾ", reportId:"റിപ്പോർട്ട് ഐഡി", date:"തീയതി", location:"സ്ഥലം", policyVersion:"നയ പതിപ്പ്", gradeA:"ഗ്രേഡ് A %", urs:"URS %", confidence:"ആത്മവിശ്വാസം", farmerAck:"കർഷക അംഗീകാരം", graderAck:"ഗ്രേഡർ അംഗീകാരം", disputeStatus:"അവലോകന നില", sampleSize:"സാമ്പിൾ വലുപ്പം", lotId:"ലോട്ട് ഐഡി", hash:"ഹാഷ്", uploadedImages:"അപ്‌ലോഡ് ചെയ്ത ചിത്രങ്ങൾ", perOnionResults:"ഉള്ളി തോറും ഫലങ്ങൾ", downloadInSelected:"ഡൗൺലോഡ്", downloadInEnglish:"ഇംഗ്ലീഷിൽ ഡൗൺലോഡ്", qrVerify:"QR പരിശോധന", openVerification:"പരിശോധന തുറക്കുക", gradingPolicy:"ഗ്രേഡിംഗ് നയം", sizeBand:"വലുപ്പ പരിധി", defectTolerances:"തകരാർ സഹിഷ്ണുത", offlineSync:"ഓഫ്‌ലൈൻ & സിങ്ക്", system:"സിസ്റ്റം", languageSettings:"ഭാഷ", changeLanguage:"ഭാഷ മാറ്റുക", myFarm:"എന്റെ കൃഷിയിടം — ഗ്രേഡിംഗ്", procOverview:"AI-സഹായിത സംഭരണം", newAssessmentTitle:"പുതിയ മൂല്യനിർണയം", farmerGraderSession:"കർഷകൻ + ഗ്രേഡർ സംയുക്തം", storedReportData:"സംഭരിച്ച റിപ്പോർട്ട്", finalReport:"അന്തിമ റിപ്പോർട്ട്", acknowledged:"അംഗീകരിച്ചു ", pending:"തീർപ്പാക്കാത്തത്", noDispute:"തർക്കമില്ല", underReview:"അവലോകനത്തിൽ", disputed:"തർക്കത്തിലായ", generatePdf:"PDF സൃഷ്ടിക്കുക · പ്രിന്റ്", markAck:"അംഗീകരിക്കുക", flagReview:"റിപ്പോർട്ട് ഫ്ലാഗ്", verification:"പരിശോധന", reportVerified:"റിപ്പോർട്ട് പരിശോധിച്ചു", }),
  or: f({ selectLanguage:"ଭାଷା ବାଛନ୍ତୁ", continue:"ଜାରି ରଖନ୍ତୁ", back:"ପଛକୁ", next:"ପରବର୍ତ୍ତୀ", dashboard:"ଡ୍ୟାସବୋର୍ଡ", assessments:"ମୂଲ୍ୟାଙ୍କନ", reviews:"ସମୀକ୍ଷା", reports:"ରିପୋର୍ଟ", policy:"ନୀତି", settings:"ସେଟିଂସ", farmer:"ଚାଷୀ", grader:"ଗ୍ରେଡର", login:"ଲଗଇନ୍", signup:"ସାଇନ୍ ଅପ୍", gmailOrPhone:"ଜିମେଲ୍ ବା ଫୋନ୍", password:"ପାସୱାର୍ଡ", sendOtp:"OTP ପଠାନ୍ତୁ", verifyOtp:"OTP ଯାଞ୍ଚ", myAssessments:"ମୋର ମୂଲ୍ୟାଙ୍କନ", allAssessments:"ସମସ୍ତ ମୂଲ୍ୟାଙ୍କନ", gradeAPercent:"ଗ୍ରେଡ୍ A %", qualityReports:"ଗୁଣବତ୍ତା ରିପୋର୍ଟ", reportId:"ରିପୋର୍ଟ ଆଇଡି", gradeA:"ଗ୍ରେଡ୍ A %", uploadedImages:"ଅପଲୋଡ୍ ଚିତ୍ର", downloadInEnglish:"ଇଂରାଜୀରେ ଡାଉନଲୋଡ୍", }),
  pa: f({ selectLanguage:"ਭਾਸ਼ਾ ਚੁਣੋ", selectLanguageDesc:"ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ — ਸੈਟਿੰਗਜ਼ ਵਿੱਚ ਕਦੇ ਵੀ ਬਦਲ ਸਕਦੇ ਹੋ।", continue:"ਜਾਰੀ ਰੱਖੋ", back:"ਪਿੱਛੇ", next:"ਅੱਗੇ", save:"ਸੇਵ", loading:"ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...", search:"ਖੋਜੋ", viewAll:"ਸਭ ਵੇਖੋ", openReport:"ਰਿਪੋਰਟ ਖੋਲ੍ਹੋ", newAssessment:"ਨਵਾਂ ਮੁਲਾਂਕਣ", dashboard:"ਡੈਸ਼ਬੋਰਡ", assessments:"ਮੁਲਾਂਕਣ", reviews:"ਸਮੀਖਿਆ", reports:"ਰਿਪੋਰਟਾਂ", policy:"ਨੀਤੀ", settings:"ਸੈਟਿੰਗਜ਼", farmer:"ਕਿਸਾਨ", grader:"ਗ੍ਰੇਡਰ", farmerDesc:"ਮੇਰੇ ਲਾਟ, ਰਿਪੋਰਟਾਂ ਅਤੇ QR ਤਸਦੀਕ", graderDesc:"ਲਾਟ ਗ੍ਰੇਡ ਕਰੋ, ਸਮੀਖਿਆ, ਨੀਤੀ", login:"ਲਾਗਇਨ", signup:"ਸਾਈਨ ਅੱਪ", logout:"ਲਾਗਆਉਟ", welcomeBack:"ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ", gmailOrPhone:"ਜੀਮੇਲ ਜਾਂ ਫੋਨ", password:"ਪਾਸਵਰਡ", fullName:"ਪੂਰਾ ਨਾਮ", sendOtp:"OTP ਭੇਜੋ", verifyOtp:"OTP ਤਸਦੀਕ", myAssessments:"ਮੇਰੇ ਮੁਲਾਂਕਣ", allAssessments:"ਸਾਰੇ ਮੁਲਾਂਕਣ", todaysAssessments:"ਅੱਜ ਦੇ ਮੁਲਾਂਕਣ", gradeAPercent:"ਗ੍ਰੇਡ A %", humanReviews:"ਮਨੁੱਖੀ ਸਮੀਖਿਆ", pendingDisputes:"ਬਕਾਇਆ ਵਿਵਾਦ", recentAssessments:"ਤਾਜ਼ਾ ਮੁਲਾਂਕਣ", qualityReports:"ਗੁਣਵੱਤਾ ਰਿਪੋਰਟਾਂ", reportId:"ਰਿਪੋਰਟ ਆਈਡੀ", date:"ਮਿਤੀ", location:"ਸਥਾਨ", gradeA:"ਗ੍ਰੇਡ A %", urs:"URS %", confidence:"ਵਿਸ਼ਵਾਸ", farmerAck:"ਕਿਸਾਨ ਪ੍ਰਵਾਨਗੀ", graderAck:"ਗ੍ਰੇਡਰ ਪ੍ਰਵਾਨਗੀ", uploadedImages:"ਅੱਪਲੋਡ ਕੀਤੀਆਂ ਤਸਵੀਰਾਂ", downloadInSelected:"ਡਾਊਨਲੋਡ", downloadInEnglish:"ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਡਾਊਨਲੋਡ", qrVerify:"QR ਤਸਦੀਕ", gradingPolicy:"ਗ੍ਰੇਡਿੰਗ ਨੀਤੀ", languageSettings:"ਭਾਸ਼ਾ", }),
  as: f({ selectLanguage:"ভাষা বাছনি কৰক", continue:"আগবাঢ়ক", back:"পিছলৈ", dashboard:"ডেশ্বব'ৰ্ড", assessments:"মূল্যায়ন", reviews:"পৰ্যালোচনা", reports:"প্ৰতিবেদন", policy:"নীতি", settings:"ছেটিংছ", farmer:"কৃষক", grader:"গ্ৰেডাৰ", login:"লগইন", signup:"চাইন আপ", gmailOrPhone:"জিমেইল বা ফোন", sendOtp:"OTP পঠাওক", myAssessments:"মোৰ মূল্যায়ন", allAssessments:"সকলো মূল্যায়ন", gradeA:"গ্ৰেড A %", reportId:"প্ৰতিবেদন আইডি", date:"তাৰিখ", location:"স্থান", uploadedImages:"আপলোড কৰা ছবি", qualityReports:"গুণগত প্ৰতিবেদন", }),
  mai: f({ selectLanguage:"भाषा चुनू", continue:"आगू बढू", dashboard:"डैशबोर्ड", assessments:"मूल्यांकन", reports:"रिपोर्ट", policy:"नीति", settings:"सेटिंग", farmer:"किसान", grader:"ग्रेडर", login:"लॉगिन", signup:"साइन अप", gmailOrPhone:"जीमेल वा फोन", sendOtp:"OTP पठाउ", myAssessments:"हमर मूल्यांकन", gradeA:"ग्रेड A %", reportId:"रिपोर्ट आईडी", uploadedImages:"अपलोड चित्र" }),
  sat: f({ selectLanguage:"ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ", continue:"ᱞᱟᱦᱟᱜ", dashboard:"ᱰᱮᱥᱵᱚᱨᱰ", assessments:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ", reports:"ᱨᱤᱯᱚᱴ", farmer:"ᱪᱟᱹᱥᱤ", grader:"ᱜᱨᱮᱰᱟᱨ", login:"ᱞᱚᱜᱤᱱ", gradeA:"ᱜᱨᱮᱰ A %", reportId:"ᱨᱤᱯᱚᱴ ᱟᱭᱰᱤ", uploadedImages:"ᱟᱯᱞᱚᱰ ᱪᱤᱛᱟᱹᱨ" }),
  ks: f({ selectLanguage:"زَبان چُنِو", continue:"جٲری", dashboard:"ڈیش بورڈ", assessments:"تشخیص", reports:"رپورٹ", policy:"پالیسی", farmer:"کسان", grader:"گریڈر", login:"لاگ ان", gradeA:"گریڈ A %", reportId:"رپورٹ آئی ڈی", uploadedImages:"اپ لوڈ تصویر" }),
  ne: f({ selectLanguage:"भाषा छान्नुहोस्", continue:"जारी राख्नुहोस्", dashboard:"ड्यासबोर्ड", assessments:"मूल्याङ्कन", reports:"रिपोर्ट", policy:"नीति", farmer:"किसान", grader:"ग्रेडर", login:"लगइन", gradeA:"ग्रेड A %", reportId:"रिपोर्ट आईडी", uploadedImages:"अपलोड गरिएका तस्बिरहरू" }),
  sd: f({ selectLanguage:"ٻولي چونڊيو", continue:"جاري رکو", dashboard:"ڊيش بورڊ", assessments:"اڃايو", reports:"رپورٽ", farmer:"هاري", grader:"گريڊر", login:"لاگ ان", gradeA:"گريڊ A %", reportId:"رپورٽ آئي ڊي", uploadedImages:"اپ لوڊ ٿيل تصويرون" }),
  kok: f({ selectLanguage:"भास निवडा", continue:"फुडे वचात", dashboard:"डॅशबोर्ड", assessments:"मूल्यांकन", reports:"अहवाल", farmer:"शेतकार", grader:"ग्रेडर", login:"लॉगिन", gradeA:"ग्रेड A %", reportId:"अहवाल आयडी", uploadedImages:"अपलोड केल्लीं प्रतिमा" }),
  doi: f({ selectLanguage:"भाषा चुनो", continue:"जारी रखो", dashboard:"डैशबोर्ड", assessments:"मूल्यांकन", reports:"रिपोर्ट", farmer:"किसान", grader:"ग्रेडर", login:"लॉगिन", gradeA:"ग्रेड A %", reportId:"रिपोर्ट आईडी", uploadedImages:"अपलोड कीतियां फोटो" }),
  mni: f({ selectLanguage:"লোল চয়ন তৌ", continue:"মখা চৎলু", dashboard:"ড্যাসবোর্ড", assessments:"মূল্যায়ন", reports:"রিপোর্ট", farmer:"লৌমী", grader:"গ্রেডার", login:"লগইন", gradeA:"গ্রেড A %", reportId:"রিপোর্ট আইডি", uploadedImages:"অপলোড তৌরবা মমি" }),
  brx: f({ selectLanguage:"राव बाछा", continue:"आगो जाथों", dashboard:"डैशबोर्ड", assessments:"साननाय", reports:"रिपोर्ट", farmer:"बिरुवा गामि", grader:"ग्रेडर", login:"लागिन", gradeA:"बर' A %", reportId:"रिपोर्ट आईडी", uploadedImages:"अपलोड खालामनाय सावगारि" }),
  sa: f({ selectLanguage:"भाषां चिनोतु", continue:"अग्रे गच्छतु", back:"पृष्ठतः", dashboard:"फलकम्", assessments:"मूल्याङ्कनम्", reviews:"समीक्षा", reports:"प्रतिवेदनम्", policy:"नीतिः", settings:"विन्यासः", farmer:"कृषकः", grader:"श्रेणीकारः", farmerDesc:"स्वस्य लाटाः प्रतिवेदनानि च", login:"प्रवेशः", signup:"पञ्जीकरणम्", gmailOrPhone:"जिमेल् वा दूरवाणी", password:"गुप्तशब्दः", sendOtp:"OTP प्रेषयतु", verifyOtp:"OTP प्रमाणयतु", myAssessments:"मम मूल्याङ्कनानि", allAssessments:"सर्वाणि मूल्याङ्कनानि", gradeA:"श्रेणी A %", reportId:"प्रतिवेदन आईडी", date:"तिथिः", location:"स्थानम्", qualityReports:"गुणवत्ता प्रतिवेदनानि", uploadedImages:"आरोपितानि चित्राणि", downloadInEnglish:"आङ्ग्ले अवतारयतु", gradingPolicy:"श्रेणी नीतिः", }),
};

const LS_LANG = "onion-setu-lang";
const I18nContext = createContext(null);
export function useI18n(){ return useContext(I18nContext); }
export function I18nProvider({ children }){
  const [lang, setLangState] = useState(()=>{
    try{ const v=localStorage.getItem(LS_LANG); if(v && dict[v]) return v; }catch{}
    return "";
  });
  const [ready, setReady] = useState(Boolean(lang));
  function setLang(code){
    if(!dict[code]) code="en";
    localStorage.setItem(LS_LANG, code);
    try{
      const raw = localStorage.getItem("onion-setu-auth-v1");
      if(raw){ const u=JSON.parse(raw); localStorage.setItem("onion-setu-auth-v1", JSON.stringify({...u, preferredLang: code})); }
    }catch{}
    setLangState(code); setReady(true); document.documentElement.lang = code;
  }
  useEffect(()=>{ if(lang) document.documentElement.lang = lang; },[lang]);
  function t(key, fallback){
    const d = dict[lang] || dict.en;
    return d[key] || dict.en[key] || fallback || key;
  }
  return (
    <I18nContext.Provider value={{ lang: lang || "en", setLang, t, languages, ready, hasChosen: Boolean(lang) }}>
      {children}
    </I18nContext.Provider>
  );
}
